spring:
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true


  kafka:
    consumer:
        bootstrap-servers: localhost:9092,localhost:9094
        key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: user-created-events
        properties:
          spring:
            json:
              trusted:
                packages: "*"